dist: xenial
language: python
python:
- '3.6'
services:
- docker
env:
- TORTUGA_BUILD_DOCKER="true" BUILD_KIT_IMAGE="univa/tortuga-build-kit:master-latest"
before_install:
- docker pull $BUILD_KIT_IMAGE
install:
- sed -i "s/^\(.*\"iteration\":\).*/\1 \"$TRAVIS_BUILD_NUMBER\",/" kit.json
- chmod -R a-w .
- docker run --rm -it -v `pwd`:/kit-src $BUILD_KIT_IMAGE tortuga kits build
- chmod a+w .
script:
- echo "Done"
deploy:
  provider: releases
  api_key:
    secure: M2Fpq5dYBHX3rmDV2tqjNZmRg2FrMfOUWSS1+MK6P0UV9MgqcRW0WbQtZp7KTVphjarrYf9qPU/m107rpmn99OTF8xZDpXriT8icVOf3sg73toZIFxnFtOeU0yOy0KJjnsZXjow0zL2KkF/Xj1hJ4rY6h23xu0kdCMBooQCYuJSuGK4ZB23aiIyfNvHO8VaHpus411loocc4+gYXPzjaEQvVhjF6YRIQUhD36EPKJRfDZMGtod5vRr65JMeGxkOkdKCbNHOa22DzJgljiD9nKoMSf7Po8uA4qeFJPqnaA/5+QLz9VuasIEGztt9lvj7MDKViySmnToQrGz7LFjavSxRrJwh5DFnmL8zhcANB3FwOVn8uZrn6ncbP9s175oXsuQ0gVz0oKJLQm+1zCLnIz7j2DyVlTwJ4Z2WT3koCor6TRzVbiHAsrYdiq7WebTdiBuSbiwjEckOlek1yZjNG1Z7lYD6dHVeWUkb+t7UzRTKIlVjnF8c3D+LoZyT+3P8E3MiM4e6kPBAwms9hdta3c3kitzFruvzfA2rd57DJJgH4UjDxncPlMWvWr2QLQFrcnTxkD14ST39NLQsrKJsEcl/ArAm7fI3GTV8yoPgdliN8ZTZ9eeC3/wy5r4njR11jBXhDnBJv8Cjyjag6mgBCZguDOWE3aHekvfaFTV7HXo8=
  file_glob: true
  file: "dist/kit-gceadapter*.tar.bz2"
  skip_cleanup: true
  draft: true
  on:
    all_branches: true
    tags: true
